import { StyleSheet, Platform } from 'react-native';

export const viewCardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    paddingTop: Platform.OS === 'web' ? 20 : 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 12,
  },
  headerButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  headerButtonText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '600',
  },
  deleteButton: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: 'rgba(239, 68, 68, 0.5)',
  },
  deleteButtonText: {
    color: '#ffcccb',
  },
  successBanner: {
    backgroundColor: '#10b981',
    padding: 12,
    alignItems: 'center',
  },
  successText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  cardSection: {
    paddingVertical: 30,
    alignItems: 'center',
  },
  cardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    width: '100%',
    maxWidth: 600,
  },
  cardContainerMobile: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 20,
  },
  cardDisplay: {
    width: 320,
    height: 200,
    borderRadius: 16,
    padding: 16,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
    boxShadow: Platform.OS === 'web' ? '0 8px 16px rgba(0, 0, 0, 0.3)' : undefined,
  },
  cardDisplayMobile: {
    width: 300,
    height: 180,
  },
  cardHeader: {
    marginBottom: 0,
  },
  cardType: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '600',
    letterSpacing: 1,
  },
  cardBank: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: 'bold',
    marginTop: 4,
  },
  cardNumber: {
    marginBottom: 8,
  },
  cardNumberText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
    letterSpacing: 2,
    textAlign: 'center',
  },
  cardBalance: {
    marginBottom: 8,
    alignItems: 'center',
  },
  balanceLabel: {
    fontSize: 9,
    color: 'rgba(255, 255, 255, 0.7)',
    fontWeight: '500',
    letterSpacing: 1,
    marginBottom: 2,
  },
  balanceAmount: {
    fontSize: 18,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  limitText: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
    marginTop: 2,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  cardInfo: {
    flex: 1,
  },
  cardHolder: {
    fontSize: 8,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  cardNameText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '600',
    marginTop: 2,
  },
  cardExpiry: {
    alignItems: 'flex-end',
  },
  expiryLabel: {
    fontSize: 8,
    color: 'rgba(255, 255, 255, 0.6)',
    fontWeight: '500',
    letterSpacing: 0.5,
  },
  expiryText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '600',
    marginTop: 2,
  },
  buttonsSection: {
    flexDirection: 'column',
    gap: 12,
    flex: 1,
  },
  buttonsSectionMobile: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 320,
    gap: 12,
    marginTop: 10,
  },
  sideButton: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    boxShadow: Platform.OS === 'web' ? '0 2px 8px rgba(0, 0, 0, 0.05)' : undefined,
    minHeight: 90,
    justifyContent: 'center',
  },
  sideButtonMobile: {
    flex: 1,
    minHeight: 80,
    padding: 12,
  },
  buttonEmoji: {
    fontSize: 24,
    marginBottom: 6,
  },
  buttonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1a202c',
    textAlign: 'center',
  },
  transactionsSection: {
    paddingBottom: 40,
  },
  transactionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  transactionsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1a202c',
  },
  viewAllButton: {
    padding: 8,
  },
  viewAllText: {
    fontSize: 14,
    color: '#667eea',
    fontWeight: '600',
  },
  billingCycleCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    boxShadow: Platform.OS === 'web' ? '0 2px 8px rgba(0, 0, 0, 0.05)' : undefined,
  },
  billingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  billingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a202c',
  },
  billingStatus: {
    backgroundColor: '#10b981',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  billingStatusText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  billingStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  billingStat: {
    flex: 1,
  },
  billingStatLabel: {
    fontSize: 14,
    color: '#718096',
    marginBottom: 4,
  },
  billingStatValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a202c',
  },
  billingDates: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f7fafc',
  },
  billingDate: {
    alignItems: 'center',
  },
  billingDateLabel: {
    fontSize: 12,
    color: '#718096',
    marginBottom: 4,
  },
  billingDateValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a202c',
  },
  cycleTransactionsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a202c',
    marginBottom: 12,
  },
  statementCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statementHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statementTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a202c',
  },
  statementStatus: {
    backgroundColor: '#667eea',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statementStatusText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  statementStats: {
    gap: 12,
  },
  statementStat: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f7fafc',
  },
  statementStatLabel: {
    fontSize: 14,
    color: '#718096',
  },
  statementStatValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a202c',
  },
  switchModalContent: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    width: '90%',
    maxWidth: 500,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  switchModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  switchModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1a202c',
  },
  switchModalBody: {
    padding: 20,
    maxHeight: 400,
  },
  switchInstruction: {
    fontSize: 16,
    color: '#4a5568',
    lineHeight: 24,
    marginBottom: 20,
  },
  cardNameHighlight: {
    fontWeight: 'bold',
    color: '#667eea',
  },
  balanceTransferSection: {
    backgroundColor: '#f0f9ff',
    borderWidth: 1,
    borderColor: '#3b82f6',
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
  },
  balanceTransferIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  balanceTransferTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e40af',
    marginBottom: 8,
  },
  balanceTransferText: {
    fontSize: 14,
    color: '#1e3a8a',
    marginBottom: 4,
  },
  cardSelectionList: {
    maxHeight: 300,
  },
  noCardsMessage: {
    textAlign: 'center',
    color: '#718096',
    fontSize: 16,
    marginVertical: 20,
  },
  createNewCardButton: {
    backgroundColor: '#10b981',
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  createNewCardText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  cardSelectionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    marginBottom: 12,
  },
  selectedCard: {
    borderColor: '#667eea',
    backgroundColor: '#f0f4ff',
  },
  selectionRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#cbd5e0',
    marginRight: 12,
  },
  selectionRadioSelected: {
    borderColor: '#667eea',
    backgroundColor: '#667eea',
  },
  selectionCardInfo: {
    flex: 1,
  },
  selectionCardName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a202c',
  },
  selectionCardDetails: {
    fontSize: 14,
    color: '#718096',
    marginTop: 2,
  },
  selectionCardBalance: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a202c',
  },
  switchModalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
});
